# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8311bd1a92ff70733c17ba30cc43e91398ae4059c7b317b4c6fb649f3924479eb576e9dfe8bbfc6633b7df3c2d67077e017cc85fbf61c6b073ce47a01c84a5b

test:
  secret_key_base: a141cc65aa6bc5ae32e2059cfde1a9fc2c8b8a95f945acc0ef4355231767a58faf65d052acb78a441f6aa197dab09791ae0d02180f6037aeef3b26e333e89cd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
